source('src/scrape_content.R')
source('test/utility_tests.R')

url <- 'https://www.expressen.se/gt/gyllenhammars-pojkvan-pantsatte-hennes-smycken/'

result <- ScrapeText(url)
expected <- 'Vi vill informera dig om vår policy som beskriver hur vi behandlar personuppgifter och cookies.
Cecilia Gyllenhammar blev sol-och-vårad av mannen hon älskade. Vid konfrontation erkände bedragaren – och författaren tvingades betala olika pantbanker för att få tillbaka sina exklusiva juveler. Nu åtalas mannen som stal smycken värda mer än 800 000 kronor. – Cecilia är ganska förmögen, som du ser på hennes efternamn, säger han i förhör. Den framgångsrika författaren Cecilia Gyllenhammar, äldsta dotter till industrimagnaten Pehr G Gyllenhammar, hade lagt skilsmässan med exmaken bakom sig. När hon stiftade bekantskap med en stilig man på en fest föll bitarna på plats för ett nytt förhållande. Han gav henne komplimanger, de hade långa intellektuella samtal och Cecilia Gyllenhammar fick höra hur fantastisk hon var. De två blev ett par, men författaren har tidigare berättat att det tidigt fanns varningssignaler i form av lögner, lån av pengar och känslan av att hon inte var den enda kvinnan i hans liv. – Men jag blundade för det. Och det har kanske med värdighet i ett förhållande att göra, man gör så gott man kan, har hon sagt. Under en semesterresa till Grekland försvann kontanter som var hennes. Gyllenhammar misstänkte pojkvännen och började gömma undan sina pengar.  Så småningom märkte hon även att flera av hennes värdefulla smycken saknades i skrinet på nattduksbordet, bland annat ett armband och ett halsband som hon ärvt från sin mamma Christina Gyllenhammar. Under en middag, där Cecilia Gyllenhammars exmake fanns med för att stötta henne, konfronterade hon slutligen honom.  Han bröt ihop och erkände att han stulit smyckena. Han förklarade att han belånat dem på tre olika pantbanker i centrala Stockholm för att lösa skulder han dragit på sig. I förhör berättar Gyllenhammar att hon fick tjata på mannen för att följa med henne till respektive pantbank för att lösa ut smyckena. Sammanlagt fick hon lägga ut mer än 50 000 kronor för att få tillbaka dem. Den 8 mars 2016 polisanmälde hon mannen – och nu är utredningen mot honom klar. På måndagen åtalades bedragaren för grov stöld. Polisens utredning visar omfattningen av smyckesstölden. Under hösten 2015 och våren 2016 misstänks mannen ha stulit juveler av Cecilia Gyllenhammar till ett sammanlagt värde av 832 000 kronor. Två av smyckena sticker ut som dyrast är ett halsband och ett armband av det exklusiva märket Bulgari. Halsbandet är i 18 karat flerfärgat guld med briljantslipade diamanter, värderat till 330 000 kronor. Armbandet i 18 karat rödguld med citrin, peridot, ametister och topaz värderas till 350 000 kronor. Mannen har inte bara erkänt för författaren, utan även i polisförhör. – Visst det är stöld, har han sagt. – Jag hade otroligt mycket skulder och visste inte hur jag skulle lösa den situationen. Och då blev det så att när jag var uppe i Stockholm så tog jag smycken av henne och gick till pantbanken.'

AssertAreEqual(result, expected)